### ISSUE TITLE
PCI-E adapter card recommendations

### ISSUE THREAD

**Issue by zielony360** [jonmason/ntb#2]
Hello,

do you have some tested PCI-E adapter card which can be used with NTB? What I've found: http://www.dolphinics.com/products/PXH810.html

**Comment by jonmason** [comment]
This will not work with the current driver.  There is no PLX driver support in Linux.

Without knowing what you are trying to do, I do not know the best solution to propose for you.

**Comment by zielony360** [comment]
I would like just to create NTB between 2 servers and use TCP/IP. What adapters are supported (at least adapters you confirmed) with the current driver?

**Comment by jonmason** [comment]
Only Intel NTB is supported.  There are no external PCI NTB adapters that are supported with the current driver.

**Comment by zielony360** [comment]
So I have servers with Intel Xeon E5-2600 and other than Intel motherboard. What more hardware do I need to use NTB Linux driver?

**Comment by jonmason** [comment]
You need motherboards that support NTB in the BIOS and 2 PCI adapters to bridge the NTB enabled PCI slots.  Intel does not sell those externally, so you would need to find an alternative source of these adapters.  This might work (completely untested) http://www.ioi.com.tw/products/proddetail.aspx?AppID=1008&CatID=106&HostID=2047&ProdID=1060158
