### ISSUE TITLE
Problem with ntb_transport + ntb_netdev

### ISSUE THREAD

**Issue by shlemisto** [jonmason/ntb#3]
Hello.

I'm working with NTB (kernel version 4.10) on Xeon D-1527 CPU and have a problem with couple ntb_transport + ntb_netdev.

On the local side I run:
sudo /etc/init.d/irqbalance stop
sudo modprobe ntb_transport dyndbg=+p
sudo modprobe ntb_netdev dyndbg=+p
sudo ifconfig eth0 192.168.1.1 up

On the remote side I run:
sudo /etc/init.d/irqbalance stop
sudo modprobe ntb_transport dyndbg=+p
sudo modprobe ntb_netdev dyndbg=+p
sudo ifconfig eth0 192.168.1.2 up

Along with these steps I run ping 192.168.1.2 and get about 2-3 successfull transmitted/received packets then get 'Destination host unreacheble'.

[dmesg.txt](https://github.com/jonmason/ntb/files/674100/dmesg.txt)

**Comment by jonmason** [comment]
We do not use the github infrastructure.  Please email the
linux-ntb@googlegroups.com mailing list with a description of the problem,
etc.
